# Generated by Django 5.0.6 on 2024-05-22 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("ingredients", models.CharField(max_length=240)),
                ("cooking_time", models.IntegerField(default=0, help_text="in min")),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("Easy", "easy"),
                            ("Medium", "medium"),
                            ("Intermediate", "intermediate"),
                            ("Hard", "hard"),
                        ],
                        default="Easy",
                        max_length=15,
                    ),
                ),
            ],
        ),
    ]
