# Generated by Django 5.0.6 on 2024-05-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0002_remove_recipe_difficulty"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="description",
            field=models.TextField(default="No Description", max_length=240),
        ),
    ]
